### ISSUE TITLE
retry timeout.

### ISSUE THREAD

**Issue by overflowz** [samueleaton/autossh#7]
Hi, I'd like to set timeout on retries. e.g when internet is off, I'd like to wait for 2-3 seconds before re-attempting the connection.

Because restarting immediately consumes a lot of CPU power, thus I'm running it on my raspberry PI, which seems overkill for that.

Regards.

**Comment by samueleaton** [comment]
This already existed in the code as `pollTimeout` but was not exposed to the public and was set to be 75ms by default. I made a simple change so its exposed now.

See [Adjusting Poll Timeout](https://github.com/samueleaton/autossh#adjusting-poll-timeout) in the README
